apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-a
spec:
  replicas: 2          # Run 2 copies — K8s balances traffic between them
  selector:
    matchLabels:
      app: service-a
  template:
    metadata:
      labels:
        app: service-a
    spec:
      containers:
      - name: service-a
        image: k8s-demo/service-a:latest
        imagePullPolicy: Never   # use local image (for Minikube)
        ports:
        - containerPort: 8001
        # K8s health checks — auto-restarts if this fails
        readinessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 10
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: service-a          # This name is the DNS hostname inside the cluster
spec:
  selector:
    app: service-a
  ports:
  - port: 8001
    targetPort: 8001
